train:
  batch_size: 32
  num_epochs: 200
  learning_rate: 0.00002
  weight_decay: 0.01
  early_stopping: True
  early_stopping_patience: 20
  cross_validation: True
  cross_validation_folds: 5

model:
  pooling: 'mean' # 'mean', 'cls', 'attn', 'gatedattn'
  n_layers: 1
  dropout: 0.3
  hidden_size: 768
  intermediate_size: 3072
  n_heads: 12
  num_classes: 1
  hidden_mlp_size: 256
  textual_model: '' 
  audio_model: 'wav2vec2' 
  pauses: True
  fusion: '' 

model_name: 'audio_only_wav2vec2'