# ノイズ追加付きwav2vec特徴量抽出設定ファイル

# 基本設定
paths:
  root_path: "dataset/diagnosis/train/audio"
  output_path: "dataset/diagnosis/train/noise_augmented_features"
  textual_data: "dataset/diagnosis/train/text_transcriptions.csv"

# モデル設定
model:
  wav2vec_model: "facebook/wav2vec2-base-960h"
  max_length: 200  # 固定値（preprocessembeddings.pyと同じ）

# データ拡張設定
augmentation_configs:
  - name: "original"
    config: null  # 元の音声（ノイズなし）
    
  - name: "gaussian_noise_light"
    config:
      add_noise: true
      noise_type: "gaussian"
      snr_db: 25.0
      noise_level: 0.05
      
  - name: "gaussian_noise_medium"
    config:
      add_noise: true
      noise_type: "gaussian"
      snr_db: 20.0
      noise_level: 0.1
      
  - name: "gaussian_noise_heavy"
    config:
      add_noise: true
      noise_type: "gaussian"
      snr_db: 15.0
      noise_level: 0.15
      
  - name: "uniform_noise"
    config:
      add_noise: true
      noise_type: "uniform"
      snr_db: 15.0
      noise_level: 0.15

# 処理設定
processing:
  skip_existing: true  # 既存ファイルをスキップするか
  batch_size: 1        # バッチサイズ（メモリ使用量調整用）
  device: "auto"       # "auto", "cuda", "cpu"

# 分類設定（audio_only.yamlを参考）
classification:
  train:
    batch_size: 64
    num_epochs: 100
    learning_rate: 0.00004  
    weight_decay: 0.01
    early_stopping: true
    early_stopping_patience: 30
    cross_validation: true
    cross_validation_folds: 5

  model:
    pooling: 'mean'  # 'mean', 'cls' (Transformer Encoder用)
    n_layers: 2      # Transformer Encoder層数
    dropout: 0.5  # 変動を減らすため下げる
    wav2vec_dim: 768
    hidden_size: 384 # Transformer Encoderの隠れ層サイズ
    intermediate_size: 3072  # Transformer Encoderのフィードフォワード層サイズ
    n_heads: 12       # マルチヘッドアテンションのヘッド数
    num_classes: 1   # ad/cnの2値分類（0=CN, 1=AD）
    hidden_mlp_size: 256  # 分類器の隠れ層サイズ
    textual_model: '' 
    audio_model: 'wav2vec2' 
    pauses: true
    fusion: '' 

  model_name: 'noise_augmented_wav2vec2'

# wandb設定
wandb:
  project: "noise-augmented-wav2vec-classification"
  entity: null  # ユーザー名を設定
  log_model: true
  log_code: true
  # ログ頻度設定
  logging:
    train_log_every: 1      # 訓練時のログ頻度（エポックごと）
    val_log_every: 1        # 評価時のログ頻度（エポックごと）
    console_log_every: 10   # コンソール出力頻度（エポックごと）
